const ICD10_CATALOG = [
{code:'A000',desc:'Cholera due to Vibrio cholerae'},
{code:'A001',desc:'Cholera due to Vibrio eltor'},
{code:'A009',desc:'Cholera unspecified'},
{code:'A0100',desc:'Typhoid fever unspecified'},
{code:'A0101',desc:'Typhoid meningitis'},
{code:'A0102',desc:'Typhoid fever with heart involvement'},
{code:'A0103',desc:'Typhoid pneumonia'},
{code:'A0104',desc:'Typhoid arthritis'},
{code:'A0105',desc:'Typhoid osteomyelitis'},
{code:'A0109',desc:'Typhoid fever with other complications'},
{code:'A011',desc:'Paratyphoid fever A'},
{code:'A012',desc:'Paratyphoid fever B'},
{code:'A013',desc:'Paratyphoid fever C'},
{code:'A014',desc:'Paratyphoid fever unspecified'},
{code:'A020',desc:'Salmonella enteritis'},
{code:'A021',desc:'Salmonella sepsis'},
{code:'A0220',desc:'Localized salmonella infection unspecified'},
{code:'A0221',desc:'Salmonella meningitis'},
{code:'A0222',desc:'Salmonella pneumonia'},
{code:'A0223',desc:'Salmonella arthritis'},
{code:'A0224',desc:'Salmonella osteomyelitis'},
{code:'A0225',desc:'Salmonella pyelonephritis'},
{code:'A0229',desc:'Salmonella with other localized infection'},
{code:'A028',desc:'Other specified salmonella infections'},
{code:'A029',desc:'Salmonella infection unspecified'},
{code:'A030',desc:'Shigellosis due to Shigella dysenteriae'},
{code:'A031',desc:'Shigellosis due to Shigella flexneri'},
{code:'A032',desc:'Shigellosis due to Shigella boydii'},
{code:'A033',desc:'Shigellosis due to Shigella sonnei'},
{code:'A038',desc:'Other shigellosis'},
{code:'A039',desc:'Shigellosis unspecified'},
{code:'A040',desc:'Enteropathogenic E coli infection'},
{code:'A041',desc:'Enterotoxigenic E coli infection'},
{code:'A042',desc:'Enteroinvasive E coli infection'},
{code:'A043',desc:'Enterohemorrhagic E coli infection'},
{code:'A044',desc:'E coli intestinal infection unspecified'},
{code:'A045',desc:'Campylobacter enteritis'},
{code:'A046',desc:'Yersinia enterocolitica enteritis'},
{code:'A047',desc:'Clostridium difficile enterocolitis'},
{code:'A048',desc:'Other bacterial intestinal infections'},
{code:'A049',desc:'Bacterial intestinal infection unspecified'},
{code:'A050',desc:'Foodborne staphylococcal intoxication'},
{code:'A051',desc:'Botulism food poisoning'},
{code:'A052',desc:'Clostridium perfringens food poisoning'},
{code:'A053',desc:'Other Clostridium food poisoning'},
{code:'A054',desc:'Vibrio parahaemolyticus food poisoning'},
{code:'A058',desc:'Other bacterial food poisoning'},
{code:'A059',desc:'Bacterial food poisoning unspecified'},
{code:'A060',desc:'Acute amebic dysentery'},
{code:'A061',desc:'Chronic intestinal amebiasis'},
{code:'A062',desc:'Amebic nondysenteric colitis'},
{code:'A063',desc:'Ameboma of intestine'},
{code:'A064',desc:'Amebic liver abscess'},
{code:'A065',desc:'Amebic lung abscess'},
{code:'A066',desc:'Amebic brain abscess'},
{code:'A067',desc:'Cutaneous amebiasis'},
{code:'A0681',desc:'Amebic cystitis'},
{code:'A0682',desc:'Other amebic genitourinary infections'},
{code:'A0689',desc:'Other amebic infections'},
{code:'A069',desc:'Amebiasis unspecified'},
{code:'A07',desc:'Other protozoal intestinal diseases'},
{code:'A080',desc:'Rotaviral enteritis'},
{code:'A0811',desc:'Acute gastroenteropathy due to Norwalk agent'},
{code:'A0819',desc:'Acute gastroenteropathy due to other Norovirus'},
{code:'A082',desc:'Adenoviral enteritis'},
{code:'A0831',desc:'Calicivirus enteritis'},
{code:'A0832',desc:'Astrovirus enteritis'},
{code:'A0833',desc:'Enterovirus enteritis'},
{code:'A0839',desc:'Other viral enteritis'},
{code:'A084',desc:'Viral intestinal infection unspecified'},
{code:'A09',desc:'Infectious gastroenteritis and colitis unspecified'},
{code:'A150',desc:'Tuberculosis of lung'},
{code:'A151',desc:'Tuberculosis of intratracheal lymph nodes'},
{code:'A152',desc:'Tuberculosis of intrathoracic lymph nodes'},
{code:'A153',desc:'Tuberculosis of larynx trachea and bronchus'},
{code:'A154',desc:'Tuberculosis of other respiratory sites'},
{code:'A155',desc:'Tuberculosis of pleural cavity'},
{code:'A156',desc:'Tuberculosis of pleural cavity with effusion'},
{code:'A157',desc:'Primary respiratory tuberculosis'},
{code:'A158',desc:'Other respiratory tuberculosis'},
{code:'A159',desc:'Respiratory tuberculosis unspecified'},
{code:'A160',desc:'Tuberculosis of lymph nodes'},
{code:'A161',desc:'Tuberculosis of bone and joint'},
{code:'A162',desc:'Tuberculosis of kidney'},
{code:'A163',desc:'Tuberculosis of other urinary organs'},
{code:'A164',desc:'Tuberculosis of epididymis'},
{code:'A165',desc:'Tuberculosis of other male genital organs'},
{code:'A167',desc:'Tuberculosis of adrenal glands'},
{code:'A168',desc:'Tuberculosis of ear'},
{code:'A169',desc:'Tuberculosis of other specified organs'},
{code:'A170',desc:'Tuberculous meningitis'},
{code:'A171',desc:'Meningeal tuberculoma'},
{code:'A178',desc:'Other tuberculosis of nervous system'},
{code:'A179',desc:'Tuberculosis of nervous system unspecified'},
{code:'A1801',desc:'Tuberculosis of bone'},
{code:'A1802',desc:'Tuberculosis of joint'},
{code:'A1803',desc:'Tuberculosis of other bones'},
{code:'A181',desc:'Tuberculosis of genitourinary system'},
{code:'A182',desc:'Tuberculous peripheral lymphadenopathy'},
{code:'A1831',desc:'Tuberculous peritonitis'},
{code:'A1832',desc:'Tuberculous enteritis'},
{code:'A1839',desc:'Tuberculosis of gastrointestinal tract'},
{code:'A184',desc:'Tuberculosis of skin and subcutaneous tissue'},
{code:'A1850',desc:'Tuberculosis of eye unspecified'},
{code:'A1851',desc:'Tuberculous episcleritis'},
{code:'A1852',desc:'Tuberculous keratitis'},
{code:'A1853',desc:'Tuberculous chorioretinitis'},
{code:'A1854',desc:'Tuberculous iridocyclitis'},
{code:'A1855',desc:'Tuberculous choroidal detachment'},
{code:'A1856',desc:'Tuberculous optic neuropathy'},
{code:'A1859',desc:'Tuberculosis of eye'},
{code:'A186',desc:'Tuberculosis of ear'},
{code:'A187',desc:'Tuberculosis of adrenal glands'},
{code:'A1881',desc:'Tuberculosis of thyroid gland'},
{code:'A1882',desc:'Tuberculosis of stomach'},
{code:'A1883',desc:'Tuberculosis of heart'},
{code:'A1884',desc:'Tuberculosis of spleen'},
{code:'A1885',desc:'Tuberculosis of lymph nodes'},
{code:'A1886',desc:'Tuberculosis of bone marrow'},
{code:'A1889',desc:'Tuberculosis of other sites'},
{code:'A190',desc:'Acute miliary tuberculosis'},
{code:'A191',desc:'Acute miliary tuberculosis of multiple sites'},
{code:'A192',desc:'Acute miliary tuberculosis unspecified'},
{code:'A198',desc:'Other miliary tuberculosis'},
{code:'A199',desc:'Miliary tuberculosis unspecified'},
{code:'A200',desc:'Bubonic plague'},
{code:'A201',desc:'Cellulocutaneous plague'},
{code:'A202',desc:'Pneumonic plague'},
{code:'A203',desc:'Plague meningitis'},
{code:'A207',desc:'Septicemic plague'},
{code:'A208',desc:'Other forms of plague'},
{code:'A209',desc:'Plague unspecified'},
{code:'A210',desc:'Ulceroglandular tularemia'},
{code:'A211',desc:'Oculoglandular tularemia'},
{code:'A212',desc:'Pulmonary tularemia'},
{code:'A213',desc:'Gastrointestinal tularemia'},
{code:'A217',desc:'Generalized tularemia'},
{code:'A218',desc:'Other tularemia'},
{code:'A219',desc:'Tularemia unspecified'},
{code:'A220',desc:'Anthrax cutaneous'},
{code:'A221',desc:'Anthrax pulmonary'},
{code:'A222',desc:'Anthrax gastrointestinal'},
{code:'A227',desc:'Anthrax sepsis'},
{code:'A228',desc:'Anthrax other forms'},
{code:'A229',desc:'Anthrax unspecified'},
{code:'A23',desc:'Brucellosis'},
{code:'A240',desc:'Glanders'},
{code:'A241',desc:'Melioidosis'},
{code:'A250',desc:'Spirillosis'},
{code:'A251',desc:'Streptobacillosis'},
{code:'A259',desc:'Rat-bite fever unspecified'},
{code:'A260',desc:'Cutaneous erysipeloid'},
{code:'A267',desc:'Erysipelothrix sepsis'},
{code:'A268',desc:'Other erysipeloid'},
{code:'A269',desc:'Erysipeloid unspecified'},
{code:'A27',desc:'Leptospirosis'},
{code:'A280',desc:'Pasteurellosis'},
{code:'A281',desc:'Cat-scratch disease'},
{code:'A282',desc:'Extraintestinal yersiniosis'},
{code:'A288',desc:'Other zoonotic bacterial diseases'},
{code:'A289',desc:'Zoonotic bacterial disease unspecified'},
{code:'A30',desc:'Leprosy'},
{code:'A31',desc:'Mycobacterial infections'},
{code:'A310',desc:'Pulmonary mycobacteria'},
{code:'A311',desc:'Cutaneous mycobacteria'},
{code:'A312',desc:'Lymphadenitis due to mycobacteria'},
{code:'A320',desc:'Listerial sepsis'},
{code:'A3211',desc:'Listerial meningitis'},
{code:'A3212',desc:'Listerial meningoencephalitis'},
{code:'A327',desc:'Listerial sepsis'},
{code:'A328',desc:'Other listerial forms'},
{code:'A329',desc:'Listeriosis unspecified'},
{code:'A33',desc:'Tetanus neonatorum'},
{code:'A34',desc:'Obstetric tetanus'},
{code:'A35',desc:'Tetanus'},
{code:'A36',desc:'Diphtheria'},
{code:'A362',desc:'Laryngeal diphtheria'},
{code:'A368',desc:'Other diphtheria'},
{code:'A369',desc:'Diphtheria unspecified'},
{code:'A37',desc:'Whooping cough'},
{code:'A38',desc:'Scarlet fever'},
{code:'A39',desc:'Meningococcal infection'},
{code:'A40',desc:'Streptococcal sepsis'},
{code:'A41',desc:'Other sepsis'},
{code:'A419',desc:'Sepsis unspecified'},
{code:'A4151',desc:'Sepsis due to E coli'},
{code:'A4152',desc:'Sepsis due to Pseudomonas'},
{code:'A42',desc:'Actinomycosis'},
{code:'A43',desc:'Nocardiosis'},
{code:'A44',desc:'Bartonellosis'},
{code:'A46',desc:'Erysipelas'},
{code:'A480',desc:'Gas gangrene'},
{code:'A481',desc:'Legionnaires disease'},
{code:'A483',desc:'Toxic shock syndrome'},
{code:'A484',desc:'Brazilian purpuric fever'},
{code:'A488',desc:'Other specified bacterial diseases'},
{code:'A49',desc:'Bacterial infection unspecified'},
{code:'A500',desc:'Early congenital syphilis symptomatic'},
{code:'A501',desc:'Early congenital syphilis latent'},
{code:'A504',desc:'Late congenital neurosyphilis'},
{code:'A505',desc:'Other late congenital syphilis'},
{code:'A509',desc:'Congenital syphilis unspecified'},
{code:'A51',desc:'Early syphilis'},
{code:'A514',desc:'Other secondary syphilis'},
{code:'A519',desc:'Early syphilis unspecified'},
{code:'A52',desc:'Late syphilis'},
{code:'A523',desc:'Neurosyphilis unspecified'},
{code:'A527',desc:'Other late symptomatic syphilis'},
{code:'A5271',desc:'Late syphilitic oculopathy'},
{code:'A5272',desc:'Syphilis of lung and bronchus'},
{code:'A5273',desc:'Syphilis of liver'},
{code:'A5274',desc:'Syphilis of kidney'},
{code:'A5275',desc:'Syphilis of musculoskeletal system'},
{code:'A5276',desc:'Syphilis of heart'},
{code:'A5277',desc:'Syphilis of other viscera'},
{code:'A5278',desc:'Syphilis of endocrine glands'},
{code:'A5279',desc:'Syphilis other organs'},
{code:'A528',desc:'Late latent syphilis'},
{code:'A529',desc:'Late syphilis unspecified'},
{code:'A53',desc:'Syphilis unspecified'},
{code:'A54',desc:'Gonococcal infection'},
{code:'A540',desc:'Gonococcal urethritis'},
{code:'A541',desc:'Gonococcal vulvovaginitis'},
{code:'A542',desc:'Gonococcal cervicitis'},
{code:'A543',desc:'Gonococcal eye infection'},
{code:'A544',desc:'Gonococcal musculoskeletal infection'},
{code:'A545',desc:'Gonococcal pharyngitis'},
{code:'A546',desc:'Gonococcal anogenital infection'},
{code:'A548',desc:'Other gonococcal infections'},
{code:'A549',desc:'Gonococcal infection unspecified'},
{code:'A55',desc:'Chlamydial lymphogranuloma'},
{code:'A56',desc:'Other chlamydial diseases'},
{code:'A560',desc:'Chlamydial lower GU infection'},
{code:'A561',desc:'Chlamydial pelvic infection'},
{code:'A562',desc:'Chlamydial urogenital site'},
{code:'A563',desc:'Chlamydial anogenital infection'},
{code:'A564',desc:'Chlamydial pharyngitis'},
{code:'A568',desc:'Chlamydial infection other sites'},
{code:'A57',desc:'Chancroid'},
{code:'A58',desc:'Granuloma inguinale'},
{code:'A59',desc:'Trichomoniasis'},
{code:'A590',desc:'Urogenital trichomoniasis'},
{code:'A598',desc:'Trichomoniasis other sites'},
{code:'A599',desc:'Trichomoniasis unspecified'},
{code:'A60',desc:'Anogenital herpesviral infection'},
{code:'A600',desc:'Herpesviral infection of genitalia'},
{code:'A601',desc:'Herpesviral infection of perianal skin'},
{code:'A609',desc:'Anogenital herpesviral infection unspecified'},
{code:'A63',desc:'Other predominantly sexually transmitted diseases'},
{code:'A630',desc:'Anogenital warts'},
{code:'A638',desc:'Other specified STDs'},
{code:'A64',desc:'Unspecified sexually transmitted disease'},
{code:'A65',desc:'Nonvenereal syphilis'},
{code:'A660',desc:'Initial lesions of yaws'},
{code:'A661',desc:'Multiple papillomata of yaws'},
{code:'A662',desc:'Other early yaws'},
{code:'A663',desc:'Hyperkeratosis of yaws'},
{code:'A664',desc:'Gummata and ulcers of yaws'},
{code:'A665',desc:'Gangosa'},
{code:'A666',desc:'Bone and joint yaws'},
{code:'A667',desc:'Other manifestations of yaws'},
{code:'A668',desc:'Latent yaws'},
{code:'A669',desc:'Yaws unspecified'},
{code:'B00',desc:'Herpesviral infections'},
{code:'B001',desc:'Herpesviral dermatitis'},
{code:'B002',desc:'Herpesviral gingivostomatitis'},
{code:'B003',desc:'Herpesviral meningitis'},
{code:'B004',desc:'Herpesviral encephalitis'},
{code:'B005',desc:'Herpesviral ocular disease'},
{code:'B007',desc:'Disseminated herpesviral disease'},
{code:'B0081',desc:'Herpesviral hepatitis'},
{code:'B0089',desc:'Other herpesviral infection'},
{code:'B009',desc:'Herpesviral infection unspecified'},
{code:'B01',desc:'Varicella'},
{code:'B010',desc:'Varicella meningitis'},
{code:'B011',desc:'Varicella encephalitis'},
{code:'B012',desc:'Varicella pneumonia'},
{code:'B018',desc:'Varicella with other complications'},
{code:'B019',desc:'Varicella without complication'},
{code:'B02',desc:'Zoster'},
{code:'B020',desc:'Zoster encephalitis'},
{code:'B021',desc:'Zoster meningitis'},
{code:'B022',desc:'Zoster with other nervous system involvement'},
{code:'B0221',desc:'Postherpetic trigeminal neuralgia'},
{code:'B0222',desc:'Postherpetic polyneuropathy'},
{code:'B0223',desc:'Postherpetic geniculate ganglionitis'},
{code:'B0224',desc:'Postherpetic myelitis'},
{code:'B0229',desc:'Postherpetic nervous system involvement'},
{code:'B023',desc:'Zoster ocular disease'},
{code:'B032',desc:'Shingles ocular'},
{code:'B027',desc:'Disseminated zoster'},
{code:'B028',desc:'Zoster with other complications'},
{code:'B029',desc:'Zoster without complications'},
{code:'B03',desc:'Smallpox'},
{code:'B04',desc:'Monkeypox'},
{code:'B05',desc:'Measles'},
{code:'B050',desc:'Measles complicated by encephalitis'},
{code:'B051',desc:'Measles complicated by meningitis'},
{code:'B052',desc:'Measles complicated by pneumonia'},
{code:'B053',desc:'Measles complicated by otitis media'},
{code:'B054',desc:'Measles with intestinal complications'},
{code:'B058',desc:'Measles with other complications'},
{code:'B059',desc:'Measles without complication'},
{code:'B06',desc:'Rubella'},
{code:'B060',desc:'Rubella with neurological complications'},
{code:'B061',desc:'Rubella with ophthalmic complications'},
{code:'B068',desc:'Rubella with other complications'},
{code:'B069',desc:'Rubella without complication'},
{code:'B07',desc:'Viral warts'},
{code:'B080',desc:'Other orthopoxvirus infections'},
{code:'B081',desc:'Molluscum contagiosum'},
{code:'B082',desc:'Exanthema subitum'},
{code:'B083',desc:'Erythema infectiosum'},
{code:'B088',desc:'Other specified viral infections'},
{code:'B09',desc:'Unspecified viral infection'},
{code:'B150',desc:'Hepatitis A with hepatic coma'},
{code:'B159',desc:'Hepatitis A without hepatic coma'},
{code:'B160',desc:'Hepatitis B acute with delta'},
{code:'B161',desc:'Hepatitis B acute without delta'},
{code:'B162',desc:'Hepatitis B without hepatic coma'},
{code:'B169',desc:'Hepatitis B acute unspecified'},
{code:'B170',desc:'Hepatitis B delta superinfection'},
{code:'B1710',desc:'Hepatitis C acute'},
{code:'B1711',desc:'Hepatitis C acute with hepatic coma'},
{code:'B172',desc:'Hepatitis E'},
{code:'B178',desc:'Other acute viral hepatitis'},
{code:'B179',desc:'Acute viral hepatitis unspecified'},
{code:'B180',desc:'Chronic hepatitis B with delta'},
{code:'B181',desc:'Chronic hepatitis B without delta'},
{code:'B182',desc:'Chronic hepatitis C'},
{code:'B188',desc:'Other chronic viral hepatitis'},
{code:'B189',desc:'Chronic viral hepatitis unspecified'},
{code:'B190',desc:'Unspecified viral hepatitis with coma'},
{code:'B1910',desc:'Unspecified viral hepatitis B without coma'},
{code:'B1920',desc:'Unspecified viral hepatitis C without coma'},
{code:'B199',desc:'Unspecified viral hepatitis without coma'},
{code:'B200',desc:'HIV disease with mycobacterial infection'},
{code:'B201',desc:'HIV disease with other bacterial infection'},
{code:'B202',desc:'HIV disease with cytomegalovirus'},
{code:'B203',desc:'HIV disease with other infections'},
{code:'B207',desc:'HIV disease with multiple infections'},
{code:'B208',desc:'HIV disease with other specified diseases'},
{code:'B209',desc:'HIV disease unspecified'},
{code:'B210',desc:'HIV disease with Kaposi sarcoma'},
{code:'B211',desc:'HIV disease with Burkitt lymphoma'},
{code:'B212',desc:'HIV disease with other non-Hodgkin lymphoma'},
{code:'B213',desc:'HIV disease with other malignant neoplasms'},
{code:'B217',desc:'HIV disease with multiple malignant neoplasms'},
{code:'B218',desc:'HIV disease with other specified diseases'},
{code:'B220',desc:'HIV disease resulting in encephalopathy'},
{code:'B221',desc:'HIV disease resulting in lymphoid interstitial pneumonitis'},
{code:'B222',desc:'HIV disease resulting in wasting syndrome'},
{code:'B227',desc:'HIV disease resulting in multiple diseases'},
{code:'B230',desc:'Acute HIV infection syndrome'},
{code:'B231',desc:'HIV disease with lymphadenopathy'},
{code:'B232',desc:'HIV disease with hematological abnormalities'},
{code:'B238',desc:'HIV disease resulting in other specified conditions'},
{code:'B24',desc:'HIV disease unspecified'},
{code:'B250',desc:'Cytomegaloviral pneumonitis'},
{code:'B251',desc:'Cytomegaloviral hepatitis'},
{code:'B252',desc:'Cytomegaloviral pancreatitis'},
{code:'B258',desc:'Other cytomegaloviral diseases'},
{code:'B259',desc:'Cytomegaloviral disease unspecified'},
{code:'B26',desc:'Mumps'},
{code:'B260',desc:'Mumps orchitis'},
{code:'B261',desc:'Mumps meningitis'},
{code:'B262',desc:'Mumps encephalitis'},
{code:'B263',desc:'Mumps pancreatitis'},
{code:'B268',desc:'Mumps with other complications'},
{code:'B269',desc:'Mumps without complication'},
{code:'B27',desc:'Infectious mononucleosis'},
{code:'B270',desc:'Gammaherpesviral mononucleosis'},
{code:'B278',desc:'Other infectious mononucleosis'},
{code:'B279',desc:'Infectious mononucleosis unspecified'},
{code:'B300',desc:'Adenoviral conjunctivitis'},
{code:'B301',desc:'Conjunctivitis due to adenovirus'},
{code:'B302',desc:'Viral pharyngoconjunctivitis'},
{code:'B303',desc:'Acute epidemic hemorrhagic conjunctivitis'},
{code:'B308',desc:'Other viral conjunctivitis'},
{code:'B309',desc:'Viral conjunctivitis unspecified'},
{code:'B330',desc:'Epidemic myalgia'},
{code:'B331',desc:'Ross River disease'},
{code:'B332',desc:'Viral carditis'},
{code:'B333',desc:'Retrovirus infections'},
{code:'B338',desc:'Other specified viral diseases'},
{code:'B340',desc:'Adenovirus infection unspecified'},
{code:'B341',desc:'Enterovirus infection unspecified'},
{code:'B342',desc:'Coronavirus infection unspecified'},
{code:'B343',desc:'Parvovirus infection unspecified'},
{code:'B344',desc:'Papovavirus infection unspecified'},
{code:'B348',desc:'Other viral infections'},
{code:'B349',desc:'Viral infection unspecified'},
{code:'B35',desc:'Dermatophytosis'},
{code:'B350',desc:'Tinea barbae'},
{code:'B351',desc:'Tinea unguium'},
{code:'B352',desc:'Tinea manuum'},
{code:'B353',desc:'Tinea pedis'},
{code:'B354',desc:'Tinea corporis'},
{code:'B355',desc:'Tinea imbricata'},
{code:'B356',desc:'Tinea cruris'},
{code:'B358',desc:'Other dermatophytoses'},
{code:'B359',desc:'Dermatophytosis unspecified'},
{code:'B36',desc:'Other superficial mycoses'},
{code:'B361',desc:'Tinea nigra'},
{code:'B362',desc:'White piedra'},
{code:'B363',desc:'Black piedra'},
{code:'B368',desc:'Other specified superficial mycoses'},
{code:'B369',desc:'Superficial mycosis unspecified'},
{code:'B37',desc:'Candidiasis'},
{code:'B370',desc:'Candidal stomatitis'},
{code:'B371',desc:'Pulmonary candidiasis'},
{code:'B372',desc:'Candidiasis of skin and nail'},
{code:'B373',desc:'Candidiasis of vulva and vagina'},
{code:'B374',desc:'Candidiasis of other urogenital sites'},
{code:'B375',desc:'Candidal meningitis'},
{code:'B376',desc:'Candidal endocarditis'},
{code:'B377',desc:'Candidal sepsis'},
{code:'B378',desc:'Candidiasis of other sites'},
{code:'B379',desc:'Candidiasis unspecified'},
{code:'B38',desc:'Coccidioidomycosis'},
{code:'B39',desc:'Histoplasmosis'},
{code:'B40',desc:'Blastomycosis'},
{code:'B41',desc:'Paracoccidioidomycosis'},
{code:'B42',desc:'Sporotrichosis'},
{code:'B427',desc:'Disseminated sporotrichosis'},
{code:'B428',desc:'Other sporotrichosis'},
{code:'B429',desc:'Sporotrichosis unspecified'},
{code:'B43',desc:'Chromomycosis'},
{code:'B44',desc:'Aspergillosis'},
{code:'B440',desc:'Invasive pulmonary aspergillosis'},
{code:'B441',desc:'Other pulmonary aspergillosis'},
{code:'B442',desc:'Tonsillar aspergillosis'},
{code:'B447',desc:'Disseminated aspergillosis'},
{code:'B448',desc:'Other aspergillosis'},
{code:'B449',desc:'Aspergillosis unspecified'},
{code:'B45',desc:'Cryptococcosis'},
{code:'B450',desc:'Pulmonary cryptococcosis'},
{code:'B451',desc:'Cerebral cryptococcosis'},
{code:'B452',desc:'Cutaneous cryptococcosis'},
{code:'B453',desc:'Osseous cryptococcosis'},
{code:'B457',desc:'Disseminated cryptococcosis'},
{code:'B458',desc:'Other cryptococcosis'},
{code:'B459',desc:'Cryptococcosis unspecified'},
{code:'B46',desc:'Zygomycosis'},
{code:'B47',desc:'Mycetoma'},
{code:'B48',desc:'Other mycoses'},
{code:'B49',desc:'Mycosis unspecified'},
{code:'B50',desc:'Plasmodium falciparum malaria'},
{code:'B51',desc:'Plasmodium vivax malaria'},
{code:'B52',desc:'Plasmodium malariae malaria'},
{code:'B53',desc:'Other specified malaria'},
{code:'B54',desc:'Malaria unspecified'},
{code:'B55',desc:'Leishmaniasis'},
{code:'B550',desc:'Visceral leishmaniasis'},
{code:'B551',desc:'Cutaneous leishmaniasis'},
{code:'B552',desc:'Mucocutaneous leishmaniasis'},
{code:'B559',desc:'Leishmaniasis unspecified'},
{code:'B56',desc:'African trypanosomiasis'},
{code:'B57',desc:'Chagas disease'},
{code:'B58',desc:'Toxoplasmosis'},
{code:'B580',desc:'Toxoplasma oculopathy'},
{code:'B581',desc:'Toxoplasma hepatitis'},
{code:'B582',desc:'Toxoplasma meningoencephalitis'},
{code:'B583',desc:'Pulmonary toxoplasmosis'},
{code:'B588',desc:'Toxoplasmosis with other organ involvement'},
{code:'B589',desc:'Toxoplasmosis unspecified'},
{code:'B59',desc:'Pneumocystosis'},
{code:'B600',desc:'Babesiosis'},
{code:'B601',desc:'Acanthamebiasis'},
{code:'B602',desc:'Naegleriasis'},
{code:'B608',desc:'Other specified protozoal diseases'},
{code:'B64',desc:'Unspecified protozoal disease'},
{code:'B65',desc:'Schistosomiasis'},
{code:'B66',desc:'Other fluke infections'},
{code:'B67',desc:'Echinococcosis'},
{code:'B68',desc:'Taeniasis'},
{code:'B69',desc:'Cysticercosis'},
{code:'B70',desc:'Diphyllobothriasis'},
{code:'B71',desc:'Other cestode infections'},
{code:'B72',desc:'Dracunculiasis'},
{code:'B73',desc:'Onchocerciasis'},
{code:'B74',desc:'Filariasis'},
{code:'B75',desc:'Trichinellosis'},
{code:'B76',desc:'Hookworm diseases'},
{code:'B77',desc:'Ascariasis'},
{code:'B78',desc:'Strongyloidiasis'},
{code:'B79',desc:'Trichuriasis'},
{code:'B80',desc:'Enterobiasis'},
{code:'B81',desc:'Other intestinal helminthiases'},
{code:'B82',desc:'Unspecified intestinal parasitism'},
{code:'B83',desc:'Other helminthiases'},
{code:'B85',desc:'Pediculosis'},
{code:'B86',desc:'Scabies'},
{code:'B87',desc:'Myiasis'},
{code:'B88',desc:'Other infestations'},
{code:'B89',desc:'Unspecified parasitic disease'},
{code:'B90',desc:'Sequelae of tuberculosis'},
{code:'B91',desc:'Sequelae of poliomyelitis'},
{code:'B92',desc:'Sequelae of leprosy'},
{code:'B94',desc:'Sequelae of other infectious diseases'},
{code:'B99',desc:'Unspecified infectious disease'},
{code:'C00',desc:'Malignant neoplasm of lip'},
{code:'C01',desc:'Malignant neoplasm of tongue'},
{code:'C02',desc:'Malignant neoplasm of mouth'},
{code:'C03',desc:'Malignant neoplasm of gum'},
{code:'C04',desc:'Malignant neoplasm of floor of mouth'},
{code:'C05',desc:'Malignant neoplasm of palate'},
{code:'C06',desc:'Malignant neoplasm of other mouth'},
{code:'C07',desc:'Malignant neoplasm of parotid'},
{code:'C08',desc:'Malignant neoplasm of salivary glands'},
{code:'C09',desc:'Malignant neoplasm of tonsil'},
{code:'C10',desc:'Malignant neoplasm of oropharynx'},
{code:'C11',desc:'Malignant neoplasm of nasopharynx'},
{code:'C12',desc:'Malignant neoplasm of pyriform sinus'},
{code:'C13',desc:'Malignant neoplasm of hypopharynx'},
{code:'C14',desc:'Malignant neoplasm of pharynx'},
{code:'C15',desc:'Malignant neoplasm of esophagus'},
{code:'C153',desc:'Malignant neoplasm upper third esophagus'},
{code:'C154',desc:'Malignant neoplasm middle third esophagus'},
{code:'C155',desc:'Malignant neoplasm lower third esophagus'},
{code:'C158',desc:'Malignant neoplasm overlapping esophagus'},
{code:'C159',desc:'Malignant neoplasm esophagus unspecified'},
{code:'C16',desc:'Malignant neoplasm of stomach'},
{code:'C160',desc:'Malignant neoplasm cardia'},
{code:'C161',desc:'Malignant neoplasm fundus'},
{code:'C162',desc:'Malignant neoplasm body of stomach'},
{code:'C163',desc:'Malignant neoplasm pyloric antrum'},
{code:'C164',desc:'Malignant neoplasm pylorus'},
{code:'C165',desc:'Malignant neoplasm lesser curvature'},
{code:'C166',desc:'Malignant neoplasm greater curvature'},
{code:'C168',desc:'Malignant neoplasm overlapping stomach'},
{code:'C169',desc:'Malignant neoplasm stomach unspecified'},
{code:'C17',desc:'Malignant neoplasm small intestine'},
{code:'C18',desc:'Malignant neoplasm colon'},
{code:'C180',desc:'Malignant neoplasm cecum'},
{code:'C181',desc:'Malignant neoplasm appendix'},
{code:'C182',desc:'Malignant neoplasm ascending colon'},
{code:'C183',desc:'Malignant neoplasm hepatic flexure'},
{code:'C184',desc:'Malignant neoplasm transverse colon'},
{code:'C185',desc:'Malignant neoplasm splenic flexure'},
{code:'C186',desc:'Malignant neoplasm descending colon'},
{code:'C187',desc:'Malignant neoplasm sigmoid colon'},
{code:'C188',desc:'Malignant neoplasm overlapping colon'},
{code:'C189',desc:'Malignant neoplasm colon unspecified'},
{code:'C19',desc:'Malignant neoplasm rectosigmoid junction'},
{code:'C20',desc:'Malignant neoplasm rectum'},
{code:'C21',desc:'Malignant neoplasm anus'},
{code:'C22',desc:'Malignant neoplasm liver'},
{code:'C220',desc:'Liver cell carcinoma'},
{code:'C221',desc:'Intrahepatic bile duct carcinoma'},
{code:'C222',desc:'Hepatoblastoma'},
{code:'C223',desc:'Angiosarcoma of liver'},
{code:'C224',desc:'Other sarcomas of liver'},
{code:'C227',desc:'Other carcinomas of liver'},
{code:'C228',desc:'Malignant neoplasm liver primary'},
{code:'C229',desc:'Malignant neoplasm liver unspecified'},
{code:'C23',desc:'Malignant neoplasm gallbladder'},
{code:'C24',desc:'Malignant neoplasm biliary tract'},
{code:'C240',desc:'Extrahepatic bile duct'},
{code:'C241',desc:'Ampulla of Vater'},
{code:'C248',desc:'Overlapping biliary'},
{code:'C249',desc:'Biliary tract unspecified'},
{code:'C25',desc:'Malignant neoplasm pancreas'},
{code:'C250',desc:'Head of pancreas'},
{code:'C251',desc:'Body of pancreas'},
{code:'C252',desc:'Tail of pancreas'},
{code:'C253',desc:'Pancreatic duct'},
{code:'C254',desc:'Endocrine pancreas'},
{code:'C257',desc:'Other specified pancreas'},
{code:'C258',desc:'Overlapping pancreas'},
{code:'C259',desc:'Pancreas unspecified'},
{code:'C26',desc:'Malignant neoplasm digestive tract'},
{code:'C300',desc:'Malignant neoplasm nasal cavity'},
{code:'C301',desc:'Malignant neoplasm middle ear'},
{code:'C31',desc:'Malignant neoplasm sinuses'},
{code:'C310',desc:'Maxillary sinus'},
{code:'C311',desc:'Ethmoid sinus'},
{code:'C312',desc:'Frontal sinus'},
{code:'C313',desc:'Sphenoid sinus'},
{code:'C318',desc:'Overlapping sinuses'},
{code:'C319',desc:'Sinus unspecified'},
{code:'C32',desc:'Malignant neoplasm larynx'},
{code:'C320',desc:'Glottis'},
{code:'C321',desc:'Supraglottis'},
{code:'C322',desc:'Subglottis'},
{code:'C323',desc:'Laryngeal cartilage'},
{code:'C328',desc:'Overlapping larynx'},
{code:'C329',desc:'Larynx unspecified'},
{code:'C33',desc:'Malignant neoplasm trachea'},
{code:'C34',desc:'Malignant neoplasm bronchus and lung'},
{code:'C340',desc:'Main bronchus'},
{code:'C341',desc:'Upper lobe bronchus'},
{code:'C342',desc:'Middle lobe bronchus'},
{code:'C343',desc:'Lower lobe bronchus'},
{code:'C348',desc:'Overlapping bronchus and lung'},
{code:'C349',desc:'Bronchus or lung unspecified'},
{code:'C37',desc:'Malignant neoplasm thymus'},
{code:'C38',desc:'Malignant neoplasm heart and mediastinum'},
{code:'C380',desc:'Heart'},
{code:'C381',desc:'Anterior mediastinum'},
{code:'C382',desc:'Posterior mediastinum'},
{code:'C383',desc:'Mediastinum part unspecified'},
{code:'C384',desc:'Pleura'},
{code:'C388',desc:'Overlapping heart mediastinum pleura'},
{code:'C39',desc:'Malignant neoplasm respiratory tract'},
{code:'C40',desc:'Malignant neoplasm bone and cartilage limb'},
{code:'C41',desc:'Malignant neoplasm bone and cartilage'},
{code:'C410',desc:'Skull and face'},
{code:'C411',desc:'Mandible'},
{code:'C412',desc:'Vertebral column'},
{code:'C413',desc:'Ribs sternum clavicle'},
{code:'C414',desc:'Pelvis sacrum coccyx'},
{code:'C418',desc:'Overlapping bone'},
{code:'C419',desc:'Bone unspecified'},
{code:'C43',desc:'Malignant melanoma of skin'},
{code:'C430',desc:'Malignant melanoma of lip'},
{code:'C431',desc:'Malignant melanoma eyelid'},
{code:'C432',desc:'Malignant melanoma ear'},
{code:'C433',desc:'Malignant melanoma face'},
{code:'C434',desc:'Malignant melanoma scalp and neck'},
{code:'C435',desc:'Malignant melanoma trunk'},
{code:'C436',desc:'Malignant melanoma upper limb'},
{code:'C437',desc:'Malignant melanoma lower limb'},
{code:'C438',desc:'Malignant melanoma overlapping'},
{code:'C439',desc:'Malignant melanoma unspecified'},
{code:'C44',desc:'Other malignant neoplasm skin'},
{code:'C442',desc:'Squamous cell carcinoma ear'},
{code:'C443',desc:'Squamous cell carcinoma face'},
{code:'C444',desc:'Squamous cell carcinoma scalp'},
{code:'C445',desc:'Squamous cell carcinoma trunk'},
{code:'C446',desc:'Squamous cell carcinoma upper limb'},
{code:'C447',desc:'Squamous cell carcinoma lower limb'},
{code:'C448',desc:'Squamous cell carcinoma overlapping'},
{code:'C449',desc:'Squamous cell carcinoma unspecified'},
{code:'C45',desc:'Mesothelioma'},
{code:'C450',desc:'Mesothelioma pleura'},
{code:'C451',desc:'Mesothelioma peritoneum'},
{code:'C452',desc:'Mesothelioma pericardium'},
{code:'C457',desc:'Mesothelioma other sites'},
{code:'C459',desc:'Mesothelioma unspecified'},
{code:'C46',desc:'Kaposi sarcoma'},
{code:'C460',desc:'Kaposi sarcoma skin'},
{code:'C461',desc:'Kaposi sarcoma soft tissue'},
{code:'C462',desc:'Kaposi sarcoma palate'},
{code:'C463',desc:'Kaposi sarcoma lymph nodes'},
{code:'C464',desc:'Kaposi sarcoma gastrointestinal'},
{code:'C465',desc:'Kaposi sarcoma pulmonary'},
{code:'C467',desc:'Kaposi sarcoma other sites'},
{code:'C469',desc:'Kaposi sarcoma unspecified'},
{code:'C47',desc:'Malignant neoplasm peripheral nerves'},
{code:'C48',desc:'Malignant neoplasm retroperitoneum'},
{code:'C49',desc:'Malignant neoplasm connective tissue'},
{code:'C490',desc:'Connective tissue head face neck'},
{code:'C491',desc:'Connective tissue upper limb'},
{code:'C492',desc:'Connective tissue lower limb'},
{code:'C493',desc:'Connective tissue thorax'},
{code:'C494',desc:'Connective tissue abdomen'},
{code:'C495',desc:'Connective tissue pelvis'},
{code:'C496',desc:'Connective tissue trunk'},
{code:'C498',desc:'Connective tissue overlapping'},
{code:'C499',desc:'Connective tissue unspecified'},
{code:'C4A',desc:'Merkel cell carcinoma'},
{code:'C4A0',desc:'Merkel cell carcinoma lip'},
{code:'C4A1',desc:'Merkel cell carcinoma eyelid'},
{code:'C4A2',desc:'Merkel cell carcinoma ear'},
{code:'C4A3',desc:'Merkel cell carcinoma face'},
{code:'C4A4',desc:'Merkel cell carcinoma scalp'},
{code:'C4A5',desc:'Merkel cell carcinoma trunk'},
{code:'C4A6',desc:'Merkel cell carcinoma upper limb'},
{code:'C4A7',desc:'Merkel cell carcinoma lower limb'},
{code:'C4A8',desc:'Merkel cell carcinoma overlapping'},
{code:'C4A9',desc:'Merkel cell carcinoma unspecified'},
{code:'C50',desc:'Malignant neoplasm breast'},
{code:'C500',desc:'Nipple and areola'},
{code:'C501',desc:'Central portion'},
{code:'C502',desc:'Upper-inner quadrant'},
{code:'C503',desc:'Lower-inner quadrant'},
{code:'C504',desc:'Upper-outer quadrant'},
{code:'C505',desc:'Lower-outer quadrant'},
{code:'C506',desc:'Axillary tail'},
{code:'C508',desc:'Overlapping breast'},
{code:'C509',desc:'Breast unspecified'},
{code:'C51',desc:'Malignant neoplasm vulva'},
{code:'C52',desc:'Malignant neoplasm vagina'},
{code:'C53',desc:'Malignant neoplasm cervix'},
{code:'C530',desc:'Endocervix'},
{code:'C531',desc:'Exocervix'},
{code:'C538',desc:'Overlapping cervix'},
{code:'C539',desc:'Cervix unspecified'},
{code:'C54',desc:'Malignant neoplasm corpus uteri'},
{code:'C540',desc:'Isthmus uteri'},
{code:'C541',desc:'Endometrium'},
{code:'C542',desc:'Myometrium'},
{code:'C543',desc:'Fundus uteri'},
{code:'C548',desc:'Overlapping corpus uteri'},
{code:'C549',desc:'Corpus uteri unspecified'},
{code:'C55',desc:'Malignant neoplasm uterus'},
{code:'C56',desc:'Malignant neoplasm ovary'},
{code:'C561',desc:'Malignant neoplasm right ovary'},
{code:'C562',desc:'Malignant neoplasm left ovary'},
{code:'C569',desc:'Malignant neoplasm ovary unspecified'},
{code:'C57',desc:'Malignant neoplasm female genital organs'},
{code:'C570',desc:'Fallopian tube'},
{code:'C571',desc:'Broad ligament'},
{code:'C572',desc:'Round ligament'},
{code:'C573',desc:'Parametrium'},
{code:'C574',desc:'Uterine adnexa'},
{code:'C577',desc:'Other female genital'},
{code:'C578',desc:'Overlapping female genital'},
{code:'C579',desc:'Female genital unspecified'},
{code:'C58',desc:'Malignant neoplasm placenta'},
{code:'C600',desc:'Malignant neoplasm prepuce'},
{code:'C601',desc:'Malignant neoplasm glans penis'},
{code:'C602',desc:'Malignant neoplasm body of penis'},
{code:'C608',desc:'Overlapping penis'},
{code:'C609',desc:'Penis unspecified'},
{code:'C61',desc:'Malignant neoplasm prostate'},
{code:'C62',desc:'Malignant neoplasm testis'},
{code:'C620',desc:'Undescended testis'},
{code:'C621',desc:'Descended testis'},
{code:'C629',desc:'Testis unspecified'},
{code:'C63',desc:'Malignant neoplasm male genital'},
{code:'C630',desc:'Epididymis'},
{code:'C631',desc:'Spermatic cord'},
{code:'C632',desc:'Scrotum'},
{code:'C637',desc:'Other male genital'},
{code:'C638',desc:'Overlapping male genital'},
{code:'C639',desc:'Male genital unspecified'},
{code:'C64',desc:'Malignant neoplasm kidney except pelvis'},
{code:'C641',desc:'Malignant neoplasm right kidney'},
{code:'C642',desc:'Malignant neoplasm left kidney'},
{code:'C649',desc:'Kidney unspecified'},
{code:'C65',desc:'Malignant neoplasm renal pelvis'},
{code:'C651',desc:'Malignant neoplasm right renal pelvis'},
{code:'C652',desc:'Malignant neoplasm left renal pelvis'},
{code:'C659',desc:'Renal pelvis unspecified'},
{code:'C66',desc:'Malignant neoplasm ureter'},
{code:'C661',desc:'Malignant neoplasm right ureter'},
{code:'C662',desc:'Malignant neoplasm left ureter'},
{code:'C669',desc:'Ureter unspecified'},
{code:'C67',desc:'Malignant neoplasm bladder'},
{code:'C670',desc:'Trigone'},
{code:'C671',desc:'Dome'},
{code:'C672',desc:'Lateral wall'},
{code:'C673',desc:'Anterior wall'},
{code:'C674',desc:'Posterior wall'},
{code:'C675',desc:'Bladder neck'},
{code:'C676',desc:'Ureteric orifice'},
{code:'C677',desc:'Urachus'},
{code:'C678',desc:'Overlapping bladder'},
{code:'C679',desc:'Bladder unspecified'},
{code:'C68',desc:'Malignant neoplasm urinary organs'},
{code:'C680',desc:'Urethra'},
{code:'C681',desc:'Paraurethral glands'},
{code:'C688',desc:'Overlapping urinary organs'},
{code:'C689',desc:'Urinary organ unspecified'},
{code:'C69',desc:'Malignant neoplasm eye'},
{code:'C690',desc:'Conjunctiva'},
{code:'C691',desc:'Cornea'},
{code:'C692',desc:'Retina'},
{code:'C693',desc:'Choroid'},
{code:'C694',desc:'Ciliary body'},
{code:'C695',desc:'Lacrimal gland'},
{code:'C696',desc:'Orbit'},
{code:'C698',desc:'Overlapping eye'},
{code:'C699',desc:'Eye unspecified'},
{code:'C7A',desc:'Malignant neuroendocrine tumors'},
{code:'C7A0',desc:'Malignant carcinoid'},
{code:'C7A1',desc:'Malignant poorly differentiated neuroendocrine'},
{code:'C7A8',desc:'Other malignant neuroendocrine'},
{code:'C7B',desc:'Secondary neuroendocrine tumors'},
{code:'C70',desc:'Malignant neoplasm meninges'},
{code:'C700',desc:'Cerebral meninges'},
{code:'C701',desc:'Spinal meninges'},
{code:'C709',desc:'Meninges unspecified'},
{code:'C71',desc:'Malignant neoplasm brain'},
{code:'C710',desc:'Cerebrum'},
{code:'C711',desc:'Frontal lobe'},
{code:'C712',desc:'Temporal lobe'},
{code:'C713',desc:'Parietal lobe'},
{code:'C714',desc:'Occipital lobe'},
{code:'C715',desc:'Cerebral ventricle'},
{code:'C716',desc:'Cerebellum'},
{code:'C717',desc:'Brain stem'},
{code:'C718',desc:'Overlapping brain'},
{code:'C719',desc:'Brain unspecified'},
{code:'C72',desc:'Malignant neoplasm spinal cord'},
{code:'C720',desc:'Spinal cord'},
{code:'C721',desc:'Cauda equina'},
{code:'C722',desc:'Olfactory nerve'},
{code:'C723',desc:'Optic nerve'},
{code:'C724',desc:'Acoustic nerve'},
{code:'C725',desc:'Cranial nerve'},
{code:'C728',desc:'Overlapping CNS'},
{code:'C729',desc:'CNS unspecified'},
{code:'C73',desc:'Malignant neoplasm thyroid'},
{code:'C74',desc:'Malignant neoplasm adrenal gland'},
{code:'C740',desc:'Cortex'},
{code:'C741',desc:'Medulla'},
{code:'C749',desc:'Adrenal unspecified'},
{code:'C75',desc:'Malignant neoplasm endocrine'},
{code:'C750',desc:'Parathyroid'},
{code:'C751',desc:'Pituitary'},
{code:'C752',desc:'Craniopharyngeal duct'},
{code:'C753',desc:'Pineal gland'},
{code:'C754',desc:'Carotid body'},
{code:'C755',desc:'Aortic body'},
{code:'C758',desc:'Pluriglandular'},
{code:'C759',desc:'Endocrine unspecified'},
{code:'C76',desc:'Malignant neoplasm other sites'},
{code:'C760',desc:'Head face neck'},
{code:'C761',desc:'Thorax'},
{code:'C762',desc:'Abdomen'},
{code:'C763',desc:'Pelvis'},
{code:'C764',desc:'Upper limb'},
{code:'C765',desc:'Lower limb'},
{code:'C768',desc:'Other specified sites'},
{code:'C77',desc:'Secondary lymph node malignancy'},
{code:'C78',desc:'Secondary respiratory malignancy'},
{code:'C79',desc:'Secondary malignancy other sites'},
{code:'C790',desc:'Secondary renal malignancy'},
{code:'C791',desc:'Secondary bladder malignancy'},
{code:'C792',desc:'Secondary skin malignancy'},
{code:'C793',desc:'Secondary brain malignancy'},
{code:'C794',desc:'Secondary nervous system malignancy'},
{code:'C7951',desc:'Secondary bone malignancy'},
{code:'C7952',desc:'Secondary bone marrow malignancy'},
{code:'C7960',desc:'Secondary ovary malignancy'},
{code:'C7961',desc:'Secondary adrenal malignancy'},
{code:'C7962',desc:'Secondary breast malignancy'},
{code:'C7963',desc:'Secondary genital malignancy'},
{code:'C7964',desc:'Secondary lymph node malignancy'},
{code:'C7965',desc:'Secondary GI malignancy'},
{code:'C7966',desc:'Secondary respiratory malignancy'},
{code:'C7967',desc:'Secondary pleural malignancy'},
{code:'C7968',desc:'Secondary peritoneal malignancy'},
{code:'C7969',desc:'Secondary malignancy other'},
{code:'C798',desc:'Secondary malignancy other'},
{code:'C799',desc:'Secondary malignancy unspecified'},
{code:'C80',desc:'Malignant neoplasm without specification'},
{code:'C800',desc:'Malignant neoplasm primary site unknown'},
{code:'C801',desc:'Malignant neoplasm unspecified'},
{code:'C802',desc:'Malignant neoplasm unspecified'},
{code:'C81',desc:'Hodgkin lymphoma'},
{code:'C810',desc:'Nodular lymphocyte predominant'},
{code:'C811',desc:'Nodular sclerosis'},
{code:'C812',desc:'Mixed cellularity'},
{code:'C813',desc:'Lymphocyte depleted'},
{code:'C814',desc:'Lymphocyte-rich'},
{code:'C817',desc:'Other Hodgkin'},
{code:'C819',desc:'Hodgkin unspecified'},
{code:'C82',desc:'Follicular lymphoma'},
{code:'C83',desc:'Non-follicular lymphoma'},
{code:'C84',desc:'Mature T/NK-cell lymphomas'},
{code:'C85',desc:'Other non-Hodgkin lymphoma'},
{code:'C86',desc:'Other T-cell lymphomas'},
{code:'C88',desc:'Malignant immunoproliferative diseases'},
{code:'C880',desc:'Waldenstrom macroglobulinemia'},
{code:'C882',desc:'Heavy chain disease'},
{code:'C883',desc:'Immunoproliferative small intestine'},
{code:'C888',desc:'Other malignant immunoproliferative'},
{code:'C889',desc:'Malignant immunoproliferative unspecified'},
{code:'C90',desc:'Multiple myeloma'},
{code:'C900',desc:'Multiple myeloma'},
{code:'C901',desc:'Plasma cell leukemia'},
{code:'C902',desc:'Extramedullary plasmacytoma'},
{code:'C903',desc:'Solitary plasmacytoma'},
{code:'C91',desc:'Lymphoid leukemia'},
{code:'C910',desc:'Acute lymphoblastic leukemia'},
{code:'C911',desc:'Chronic lymphocytic leukemia'},
{code:'C912',desc:'Subacute lymphocytic leukemia'},
{code:'C913',desc:'Prolymphocytic leukemia'},
{code:'C914',desc:'Hairy cell leukemia'},
{code:'C915',desc:'Adult T-cell leukemia'},
{code:'C916',desc:'Other lymphoid leukemia'},
{code:'C919',desc:'Lymphoid leukemia unspecified'},
{code:'C92',desc:'Myeloid leukemia'},
{code:'C920',desc:'Acute myeloid leukemia'},
{code:'C921',desc:'Chronic myeloid leukemia'},
{code:'C922',desc:'Subacute myeloid leukemia'},
{code:'C923',desc:'Myeloid sarcoma'},
{code:'C924',desc:'Acute promyelocytic leukemia'},
{code:'C925',desc:'Acute myelomonocytic leukemia'},
{code:'C926',desc:'Acute monoblastic leukemia'},
{code:'C929',desc:'Myeloid leukemia unspecified'},
{code:'C93',desc:'Monocytic leukemia'},
{code:'C930',desc:'Acute monocytic leukemia'},
{code:'C931',desc:'Chronic monocytic leukemia'},
{code:'C932',desc:'Subacute monocytic leukemia'},
{code:'C939',desc:'Monocytic leukemia unspecified'},
{code:'C94',desc:'Other leukemias'},
{code:'C940',desc:'Acute erythroid leukemia'},
{code:'C942',desc:'Acute megakaryoblastic leukemia'},
{code:'C943',desc:'Mast cell leukemia'},
{code:'C944',desc:'Acute panmyelosis'},
{code:'C946',desc:'Myelodysplastic syndrome'},
{code:'C948',desc:'Other specified leukemias'},
{code:'C95',desc:'Leukemia unspecified'},
{code:'C950',desc:'Acute leukemia unspecified'},
{code:'C951',desc:'Chronic leukemia unspecified'},
{code:'C959',desc:'Leukemia unspecified'},
{code:'C96',desc:'Other malignant neoplasms of lymphoid tissue'},
{code:'C96A',desc:'Histiocytic sarcoma'},
{code:'C96Z',desc:'Other specified malignant neoplasms lymphoid'},
{code:'D00',desc:'Carcinoma in situ oral cavity'},
{code:'D01',desc:'Carcinoma in situ digestive'},
{code:'D010',desc:'Esophagus'},
{code:'D011',desc:'Stomach'},
{code:'D012',desc:'Colon'},
{code:'D013',desc:'Rectum'},
{code:'D014',desc:'Small intestine'},
{code:'D015',desc:'Liver and biliary'},
{code:'D017',desc:'Pancreas'},
{code:'D019',desc:'Digestive unspecified'},
{code:'D02',desc:'Carcinoma in situ respiratory'},
{code:'D020',desc:'Larynx'},
{code:'D021',desc:'Trachea'},
{code:'D022',desc:'Bronchus and lung'},
{code:'D023',desc:'Bronchus'},
{code:'D024',desc:'Respiratory unspecified'},
{code:'D03',desc:'Melanoma in situ'},
{code:'D04',desc:'Carcinoma in situ skin'},
{code:'D05',desc:'Carcinoma in situ breast'},
{code:'D050',desc:'Lobular in situ'},
{code:'D051',desc:'Ductal in situ'},
{code:'D057',desc:'Other breast in situ'},
{code:'D059',desc:'Breast in situ unspecified'},
{code:'D06',desc:'Carcinoma in situ cervix'},
{code:'D060',desc:'Endocervix'},
{code:'D061',desc:'Exocervix'},
{code:'D067',desc:'Other cervix'},
{code:'D069',desc:'Cervix unspecified'},
{code:'D07',desc:'Carcinoma in situ genital'},
{code:'D070',desc:'Endometrium'},
{code:'D071',desc:'Vulva'},
{code:'D072',desc:'Vagina'},
{code:'D073',desc:'Ovary'},
{code:'D074',desc:'Penis'},
{code:'D075',desc:'Prostate'},
{code:'D076',desc:'Male genital'},
{code:'D078',desc:'Female genital'},
{code:'D079',desc:'Genital unspecified'},
{code:'D09',desc:'Carcinoma in situ other sites'},
{code:'D090',desc:'Bladder'},
{code:'D091',desc:'Eye'},
{code:'D092',desc:'Thyroid'},
{code:'D093',desc:'Adrenal'},
{code:'D098',desc:'Other specified'},
{code:'D099',desc:'Carcinoma in situ unspecified'},
{code:'D10',desc:'Benign neoplasm mouth'},
{code:'D100',desc:'Lip'},
{code:'D101',desc:'Tongue'},
{code:'D102',desc:'Floor of mouth'},
{code:'D103',desc:'Mouth'},
{code:'D104',desc:'Tonsil'},
{code:'D105',desc:'Pharynx'},
{code:'D106',desc:'Nasopharynx'},
{code:'D107',desc:'Hypopharynx'},
{code:'D108',desc:'Oral cavity'},
{code:'D109',desc:'Oral unspecified'},
{code:'D11',desc:'Benign neoplasm salivary'},
{code:'D110',desc:'Parotid'},
{code:'D117',desc:'Other salivary'},
{code:'D119',desc:'Salivary unspecified'},
{code:'D12',desc:'Benign neoplasm colon'},
{code:'D120',desc:'Cecum'},
{code:'D121',desc:'Appendix'},
{code:'D122',desc:'Ascending colon'},
{code:'D123',desc:'Transverse colon'},
{code:'D124',desc:'Descending colon'},
{code:'D125',desc:'Sigmoid colon'},
{code:'D126',desc:'Colon unspecified'},
{code:'D127',desc:'Rectosigmoid junction'},
{code:'D128',desc:'Rectum'},
{code:'D129',desc:'Anal canal'},
{code:'D130',desc:'Benign neoplasm esophagus'},
{code:'D131',desc:'Benign neoplasm stomach'},
{code:'D132',desc:'Benign neoplasm duodenum'},
{code:'D133',desc:'Benign neoplasm small intestine'},
{code:'D134',desc:'Benign neoplasm liver'},
{code:'D135',desc:'Benign neoplasm biliary'},
{code:'D136',desc:'Benign neoplasm pancreas'},
{code:'D137',desc:'Benign neoplasm endocrine pancreas'},
{code:'D139',desc:'Benign neoplasm digestive'},
{code:'D14',desc:'Benign neoplasm respiratory'},
{code:'D140',desc:'Larynx'},
{code:'D141',desc:'Trachea'},
{code:'D142',desc:'Bronchus and lung'},
{code:'D143',desc:'Bronchus'},
{code:'D144',desc:'Respiratory'},
{code:'D15',desc:'Benign neoplasm thoracic'},
{code:'D150',desc:'Thymus'},
{code:'D151',desc:'Heart'},
{code:'D152',desc:'Mediastinum'},
{code:'D157',desc:'Thoracic'},
{code:'D159',desc:'Thoracic unspecified'},
{code:'D16',desc:'Benign neoplasm bone'},
{code:'D160',desc:'Skull and face'},
{code:'D161',desc:'Mandible'},
{code:'D162',desc:'Vertebra'},
{code:'D163',desc:'Rib sternum clavicle'},
{code:'D164',desc:'Pelvis'},
{code:'D165',desc:'Upper limb'},
{code:'D166',desc:'Lower limb'},
{code:'D168',desc:'Overlapping bone'},
{code:'D169',desc:'Bone unspecified'},
{code:'D17',desc:'Benign lipomatous neoplasm'},
{code:'D170',desc:'Skin and subcutaneous'},
{code:'D171',desc:'Intrathoracic'},
{code:'D172',desc:'Intra-abdominal'},
{code:'D173',desc:'Spermatic cord'},
{code:'D174',desc:'Other sites'},
{code:'D177',desc:'Lipomatous'},
{code:'D179',desc:'Lipomatous unspecified'},
{code:'D18',desc:'Hemangioma'},
{code:'D180',desc:'Hemangioma any site'},
{code:'D1800',desc:'Hemangioma unspecified'},
{code:'D1801',desc:'Hemangioma skin'},
{code:'D1802',desc:'Hemangioma intracranial'},
{code:'D1803',desc:'Hemangioma intra-abdominal'},
{code:'D1808',desc:'Hemangioma other sites'},
{code:'D19',desc:'Benign neoplasm mesothelial'},
{code:'D190',desc:'Pleura'},
{code:'D191',desc:'Peritoneum'},
{code:'D197',desc:'Mesothelial'},
{code:'D199',desc:'Mesothelial unspecified'},
{code:'D20',desc:'Benign neoplasm retroperitoneum'},
{code:'D200',desc:'Retroperitoneum'},
{code:'D201',desc:'Peritoneum'},
{code:'D21',desc:'Benign neoplasm connective tissue'},
{code:'D210',desc:'Head face neck'},
{code:'D211',desc:'Upper limb'},
{code:'D212',desc:'Lower limb'},
{code:'D213',desc:'Thorax'},
{code:'D214',desc:'Abdomen'},
{code:'D215',desc:'Pelvis'},
{code:'D216',desc:'Trunk'},
{code:'D218',desc:'Overlapping'},
{code:'D219',desc:'Connective tissue unspecified'},
{code:'D22',desc:'Melanocytic nevi'},
{code:'D23',desc:'Benign neoplasm skin'},
{code:'D24',desc:'Benign neoplasm breast'},
{code:'D241',desc:'Benign neoplasm right breast'},
{code:'D242',desc:'Benign neoplasm left breast'},
{code:'D249',desc:'Breast unspecified'},
{code:'D25',desc:'Leiomyoma of uterus'},
{code:'D250',desc:'Submucous'},
{code:'D251',desc:'Intramural'},
{code:'D252',desc:'Subserosal'},
{code:'D259',desc:'Leiomyoma unspecified'},
{code:'D26',desc:'Benign neoplasm uterus'},
{code:'D260',desc:'Cervix'},
{code:'D261',desc:'Corpus uteri'},
{code:'D267',desc:'Uterine'},
{code:'D269',desc:'Uterus unspecified'},
{code:'D27',desc:'Benign neoplasm ovary'},
{code:'D271',desc:'Benign neoplasm right ovary'},
{code:'D272',desc:'Benign neoplasm left ovary'},
{code:'D279',desc:'Ovary unspecified'},
{code:'D28',desc:'Benign neoplasm female genital'},
{code:'D280',desc:'Vulva'},
{code:'D281',desc:'Vagina'},
{code:'D282',desc:'Fallopian tube'},
{code:'D283',desc:'Broad ligament'},
{code:'D284',desc:'Parametrium'},
{code:'D287',desc:'Other female genital'},
{code:'D289',desc:'Female genital unspecified'},
{code:'D29',desc:'Benign neoplasm male genital'},
{code:'D290',desc:'Penis'},
{code:'D291',desc:'Prostate'},
{code:'D292',desc:'Testis'},
{code:'D293',desc:'Epididymis'},
{code:'D294',desc:'Scrotum'},
{code:'D298',desc:'Other male'},
{code:'D299',desc:'Male genital unspecified'},
{code:'D30',desc:'Benign neoplasm urinary'},
{code:'D300',desc:'Kidney'},
{code:'D301',desc:'Renal pelvis'},
{code:'D302',desc:'Ureter'},
{code:'D303',desc:'Bladder'},
{code:'D304',desc:'Urethra'},
{code:'D308',desc:'Other urinary'},
{code:'D309',desc:'Urinary unspecified'},
{code:'D31',desc:'Benign neoplasm eye'},
{code:'D32',desc:'Benign neoplasm meninges'},
{code:'D33',desc:'Benign neoplasm brain'},
{code:'D34',desc:'Benign neoplasm thyroid'},
{code:'D35',desc:'Benign neoplasm endocrine'},
{code:'D350',desc:'Adrenal'},
{code:'D351',desc:'Parathyroid'},
{code:'D352',desc:'Pituitary'},
{code:'D353',desc:'Craniopharyngeal duct'},
{code:'D354',desc:'Pineal'},
{code:'D355',desc:'Carotid body'},
{code:'D356',desc:'Aortic body'},
{code:'D357',desc:'Pluriglandular'},
{code:'D358',desc:'Other endocrine'},
{code:'D359',desc:'Endocrine unspecified'},
{code:'D36',desc:'Benign neoplasm other sites'},
{code:'D360',desc:'Lymph node'},
{code:'D361',desc:'Peripheral nerve'},
{code:'D367',desc:'Other sites'},
{code:'D369',desc:'Benign neoplasm unspecified'},
{code:'D37',desc:'Neoplasm uncertain oral'},
{code:'D370',desc:'Lip oral cavity pharynx'},
{code:'D371',desc:'Stomach'},
{code:'D372',desc:'Small intestine'},
{code:'D373',desc:'Appendix'},
{code:'D374',desc:'Colon'},
{code:'D375',desc:'Rectum'},
{code:'D376',desc:'Liver'},
{code:'D377',desc:'Pancreas'},
{code:'D379',desc:'Digestive uncertain'},
{code:'D38',desc:'Neoplasm uncertain respiratory'},
{code:'D39',desc:'Neoplasm uncertain female genital'},
{code:'D40',desc:'Neoplasm uncertain male genital'},
{code:'D41',desc:'Neoplasm uncertain urinary'},
{code:'D42',desc:'Neoplasm uncertain meninges'},
{code:'D43',desc:'Neoplasm uncertain brain'},
{code:'D44',desc:'Neoplasm uncertain endocrine'},
{code:'D45',desc:'Polycythemia vera'},
{code:'D46',desc:'Myelodysplastic syndromes'},
{code:'D460',desc:'Refractory anemia without sideroblasts'},
{code:'D461',desc:'Refractory anemia with sideroblasts'},
{code:'D4620',desc:'Refractory anemia with excess blasts'},
{code:'D4621',desc:'MDS with 5q deletion'},
{code:'D4622',desc:'MDS with ring sideroblasts'},
{code:'D4623',desc:'MDS with multilineage dysplasia'},
{code:'D4624',desc:'MDS with single lineage dysplasia'},
{code:'D4625',desc:'MDS with excess blasts'},
{code:'D4626',desc:'MDS with fibrosis'},
{code:'D4627',desc:'MDS unclassifiable'},
{code:'D4629',desc:'MDS unspecified'},
{code:'D469',desc:'Myelodysplastic syndrome unspecified'},
{code:'D47',desc:'Other lymphoid neoplasms'},
{code:'D470',desc:'Mast cell neoplasms'},
{code:'D471',desc:'Chronic myeloproliferative disease'},
{code:'D472',desc:'Monoclonal gammopathy'},
{code:'D473',desc:'Essential thrombocythemia'},
{code:'D474',desc:'Osteomyelofibrosis'},
{code:'D477',desc:'Other lymphoid'},
{code:'D479',desc:'Lymphoid neoplasm unspecified'},
{code:'D48',desc:'Neoplasm uncertain other sites'},
{code:'D480',desc:'Bone and cartilage'},
{code:'D481',desc:'Connective tissue'},
{code:'D482',desc:'Peripheral nerve'},
{code:'D483',desc:'Retroperitoneum'},
{code:'D484',desc:'Peritoneum'},
{code:'D485',desc:'Skin'},
{code:'D486',desc:'Breast'},
{code:'D487',desc:'Other sites'},
{code:'D489',desc:'Neoplasm uncertain unspecified'},
{code:'D49',desc:'Neoplasm unspecified behavior'},
{code:'D490',desc:'Digestive'},
{code:'D491',desc:'Respiratory'},
{code:'D492',desc:'Bone and cartilage'},
{code:'D493',desc:'Breast'},
{code:'D494',desc:'Bladder'},
{code:'D495',desc:'Female genital'},
{code:'D496',desc:'Male genital'},
{code:'D497',desc:'Endocrine'},
{code:'D498',desc:'Other sites'},
{code:'D499',desc:'Unspecified'},
];
